"""Core contracts shared by every FinTwinOS module: types, config, audit, interfaces."""

from fintwinos.core.audit import AuditRecord, AuditTrail
from fintwinos.core.config import Settings, get_settings
from fintwinos.core.errors import (
    ApprovalRequired,
    FinTwinError,
    PolicyViolation,
    SchemaValidationError,
    ToolNotFound,
)
from fintwinos.core.types import (
    Account,
    Alert,
    ApprovalStatus,
    ApprovalToken,
    CaseRecord,
    CaseStatus,
    Customer,
    Decision,
    EntityRef,
    EventEnvelope,
    Instrument,
    LegalEntity,
    PolicyDoc,
    Position,
    Provenance,
    RiskTier,
    Scenario,
    SideEffectClass,
    SimulationResult,
    ToolBand,
    ToolResult,
    Trade,
    utcnow,
)

__all__ = [
    "Account",
    "Alert",
    "ApprovalRequired",
    "ApprovalStatus",
    "ApprovalToken",
    "AuditRecord",
    "AuditTrail",
    "CaseRecord",
    "CaseStatus",
    "Customer",
    "Decision",
    "EntityRef",
    "EventEnvelope",
    "FinTwinError",
    "Instrument",
    "LegalEntity",
    "PolicyDoc",
    "PolicyViolation",
    "Position",
    "Provenance",
    "RiskTier",
    "Scenario",
    "SchemaValidationError",
    "Settings",
    "SideEffectClass",
    "SimulationResult",
    "ToolBand",
    "ToolNotFound",
    "ToolResult",
    "Trade",
    "get_settings",
    "utcnow",
]
