"""Export canonical entity JSON Schemas to the repo-level ``schemas/`` directory."""

from __future__ import annotations

import json
from pathlib import Path

from fintwinos.core.types import CANONICAL_MODELS


def export_all(out_dir: Path | str = "schemas") -> list[Path]:
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    for model in CANONICAL_MODELS:
        schema = model.model_json_schema()
        path = out / f"{_snake(model.__name__)}.schema.json"
        path.write_text(json.dumps(schema, indent=2) + "\n", encoding="utf-8")
        written.append(path)
    index = {
        "$comment": "FinTwinOS canonical entity schemas — generated by fintwinos export-schemas",
        "schemas": [p.name for p in written],
    }
    index_path = out / "index.json"
    index_path.write_text(json.dumps(index, indent=2) + "\n", encoding="utf-8")
    written.append(index_path)
    return written


def _snake(name: str) -> str:
    chars: list[str] = []
    for i, ch in enumerate(name):
        if ch.isupper() and i > 0 and not name[i - 1].isupper():
            chars.append("_")
        chars.append(ch.lower())
    return "".join(chars)
