"""Seeded generator of a small, coherent synthetic demo book.

Produces a self-consistent financial institution in miniature, entirely as
:class:`EventEnvelope`s flowing through the normal ingestion path (so demo
loading exercises exactly the same machinery as production connectors):

- 40 customers (25 corporates, 15 retail) — six of which form a structured
  money-laundering ring cycling sub-threshold transfers through 6 linked
  accounts;
- 60 accounts across USD/EUR/GBP;
- 8 instruments with daily mid-price series generated by geometric Brownian
  motion with GARCH(1,1)-style volatility clustering;
- 200 trades and the resulting non-zero positions;
- 6 open cases (AML structuring, complaints, a limit breach, a KYC refresh
  and a fraud review) with searchable narratives;
- 5 policy documents (AML escalation, liquidity contingency, complaints
  handling, trading limits, model governance);
- 30-day USD/EUR/GBP cash ladders as time series.

Everything is driven by a single ``numpy.random.default_rng(seed)`` and fixed
identifier counters, so the same seed always yields a byte-identical twin
(verified by snapshot content hash).
"""

from __future__ import annotations

import math
from datetime import UTC, datetime, timedelta
from typing import Any

import numpy as np
import pandas as pd

from fintwinos.core.interfaces import EventIngestor
from fintwinos.core.types import EntityRef, EventEnvelope, Provenance

DEMO_EPISODE_ID = "demo"
DEMO_SOURCE = "demo_book"

_BASE_DATE = datetime(2026, 1, 5, tzinfo=UTC)  # a Monday
_N_PRICE_DAYS = 120
_N_TRADES = 200
_N_CASH_BUCKETS = 30
_RING_CUSTOMER_INDICES = range(19, 25)  # cus_0020 .. cus_0025
_SECOND_ACCOUNT_INDICES = list(range(0, 19)) + [25]  # 20 extra accounts -> 60 total

#: (instrument_id, symbol, asset_class, currency)
INSTRUMENTS: list[tuple[str, str, str, str]] = [
    ("ins_ALPH", "ALPH", "equity", "USD"),
    ("ins_BRVO", "BRVO", "equity", "USD"),
    ("ins_CRWN", "CRWN", "equity", "GBP"),
    ("ins_DLTA", "DLTA", "equity", "EUR"),
    ("ins_ECHO", "ECHO", "equity", "USD"),
    ("ins_FOXT", "FOXT", "equity", "GBP"),
    ("ins_GILT", "GILT", "govt_bond", "GBP"),
    ("ins_HLIX", "HLIX", "commodity_etf", "USD"),
]

# Unique leading tokens everywhere so distinct demo entities never fuzzy-merge.
_CORP_FIRST = [
    "Acme", "Borealis", "Cobalt", "Dunmore", "Eastgate", "Fenwick", "Gallium",
    "Harrowgate", "Ironside", "Juniper", "Kestrel", "Lumenor", "Meridian",
    "Northgate", "Oakfield", "Pinemont", "Quartzline", "Redwood", "Silverton",
    "Thornbury", "Umberline", "Vantage", "Westbrook", "Yellowtail", "Zephyr",
]
_CORP_LINES = [
    "Trading", "Holdings", "Logistics", "Capital", "Imports",
    "Textiles", "Foods", "Energy", "Marine", "Analytics",
]
_CORP_SUFFIXES = ["Ltd", "Limited", "PLC", "Group", "LLP"]
_RETAIL_NAMES = [
    "Alice Hartley", "Benedict Owusu", "Carmen Delgado", "Devraj Nair",
    "Eleni Papadopoulos", "Farah Iqbal", "Gareth Llewellyn", "Hannah Sorensen",
    "Imran Chowdhury", "Josephine Mbeki", "Klaus Reinhardt", "Lucia Moretti",
    "Magnus Eriksen", "Noor Alsayed", "Olusegun Adeyemi",
]

_CURRENCIES = ["USD", "EUR", "GBP"]
_COUNTRIES = ["GB", "US", "DE", "FR", "NL", "IE", "ES"]
_ACCOUNT_TYPES = ["deposit", "trading", "savings"]

_POLICIES: list[dict[str, Any]] = [
    {
        "policy_id": "pol_aml_escalation",
        "title": "AML Escalation Procedure",
        "tags": ["aml", "financial-crime", "escalation"],
        "body": (
            "Purpose. This procedure defines how anti money laundering alerts are "
            "triaged, investigated and escalated to the Money Laundering Reporting "
            "Officer (MLRO).\n\n"
            "Triage. Every structuring, velocity or sanctions alert must be triaged "
            "within one business day. Analysts assess the alert score, the customer "
            "risk rating and the transaction pattern. Transfers deliberately kept "
            "below the 10,000 reporting threshold (structuring or smurfing), rapid "
            "circular movement of funds between linked accounts, and activity that "
            "is inconsistent with the documented customer profile are mandatory "
            "escalation triggers.\n\n"
            "Escalation. Confirmed suspicious activity is escalated to the MLRO with "
            "a written summary of the suspicious transactions, the entities involved "
            "and the supporting evidence from the twin. The MLRO decides within two "
            "business days whether to file a Suspicious Activity Report. Accounts "
            "may only be frozen with MLRO approval and dual control; tipping off the "
            "customer is a criminal offence.\n\n"
            "Record keeping. All triage decisions, escalations and reports are "
            "appended to the audit trail and retained for six years."
        ),
    },
    {
        "policy_id": "pol_liquidity_contingency",
        "title": "Liquidity Contingency Funding Plan",
        "tags": ["liquidity", "treasury", "stress"],
        "body": (
            "Purpose. This plan sets out the early-warning indicators, escalation "
            "ladder and funding actions to be taken when intraday or term liquidity "
            "comes under stress.\n\n"
            "Indicators. Treasury monitors the USD, EUR and GBP cash ladders daily. "
            "A projected cumulative outflow exceeding 15 percent of the liquid asset "
            "buffer within five business days, a counterparty funding withdrawal, or "
            "a two-notch ratings downgrade each trigger contingency status.\n\n"
            "Actions. Stage one: extend the maturity profile of new funding and halt "
            "discretionary asset growth. Stage two: draw committed facilities and "
            "monetise high-quality liquid assets via repo. Stage three: activate the "
            "recovery plan and notify the regulator. Each stage requires sign-off by "
            "the Treasurer and the Chief Risk Officer.\n\n"
            "Testing. The plan is tested twice a year through a simulated funding "
            "stress, and the cash ladder projections are back-tested monthly against "
            "realised flows."
        ),
    },
    {
        "policy_id": "pol_complaints_handling",
        "title": "Complaints Handling Standard",
        "tags": ["conduct", "complaints", "customer"],
        "body": (
            "Purpose. Fair, prompt and consistent handling of customer complaints "
            "is a regulatory obligation and a conduct priority.\n\n"
            "Acknowledgement. Every complaint — written, telephoned or raised in "
            "branch — is logged as a case within 24 hours and acknowledged to the "
            "customer within three business days, naming the case handler.\n\n"
            "Investigation. The handler gathers the relevant account records, "
            "payment traces and communications, and assesses redress in line with "
            "the published remediation matrix. Complaints involving vulnerable "
            "customers, delayed payments or disputed fees above 500 are reviewed by "
            "a senior handler. A final response is due within eight weeks; if it "
            "cannot be met, the customer must be told of their right to refer the "
            "matter to the ombudsman.\n\n"
            "Root cause. Complaint categories are analysed quarterly and systemic "
            "root causes are reported to the conduct committee with remediation "
            "owners and deadlines."
        ),
    },
    {
        "policy_id": "pol_trading_limits",
        "title": "Trading Limits and Mandate Policy",
        "tags": ["market-risk", "limits", "trading"],
        "body": (
            "Purpose. This policy defines the limit framework governing all trading "
            "activity in client and house accounts.\n\n"
            "Limit structure. Each trading account carries a daily gross notional "
            "limit, a single-order notional limit and an open-position concentration "
            "limit per instrument. Limits are set according to the account's mandate "
            "and the customer's risk rating, and are loaded into the pre-trade "
            "checks before market open.\n\n"
            "Breaches. A passive breach caused by market moves must be reduced to "
            "within limit by the close of the next business day. An active breach — "
            "an order that takes exposure beyond limit — is a limit breach case: the "
            "desk supervisor is notified immediately, the position is frozen for new "
            "risk, and the breach is reported to market risk with a remediation "
            "plan. Repeated breaches trigger a mandate review.\n\n"
            "Overrides. Temporary limit increases require dual approval from the "
            "desk head and market risk, are time-boxed, and are recorded in the "
            "audit trail."
        ),
    },
    {
        "policy_id": "pol_model_governance",
        "title": "Model Governance and Validation Standard",
        "tags": ["model-risk", "governance", "validation"],
        "body": (
            "Purpose. All models — pricing, risk, AML detection, simulation and "
            "machine-learnt decision models — are governed under this standard.\n\n"
            "Inventory. Every model is registered in the model inventory with an "
            "owner, a tier reflecting its materiality, its assumptions version and "
            "its approved use. Using a model outside its approved scope is a "
            "governance breach.\n\n"
            "Validation. New models and material changes are independently "
            "validated before use: conceptual soundness, data quality, calibration "
            "evidence, benchmark comparison and sensitivity analysis. Simulators "
            "must publish confidence intervals and calibration diagnostics, never "
            "bare point estimates. Tier-one models are revalidated annually.\n\n"
            "Monitoring. Owners monitor performance against calibration thresholds; "
            "breaches trigger investigation and, where material, suspension of the "
            "model pending revalidation. Decisions taken on model output remain "
            "subject to the human approval gates defined in the tool policy."
        ),
    },
]


_CALENDAR = pd.bdate_range(_BASE_DATE.date(), periods=_N_PRICE_DAYS + _N_CASH_BUCKETS)


def _bday(index: int, hour: int = 16, minute: int = 30) -> datetime:
    """The ``index``-th business day of the demo calendar at a fixed UTC time."""
    stamp = _CALENDAR[index]
    return datetime(stamp.year, stamp.month, stamp.day, hour, minute, tzinfo=UTC)


class _DemoBookBuilder:
    """Stateful builder: one rng, one envelope counter, fully deterministic."""

    def __init__(self, seed: int) -> None:
        self.seed = seed
        self.rng = np.random.default_rng(seed)
        self.envelopes: list[EventEnvelope] = []
        self._event_counter = 0
        self.customers: list[dict[str, Any]] = []
        self.accounts: list[dict[str, Any]] = []
        self.account_by_customer: dict[str, list[str]] = {}
        self.prices: dict[str, list[float]] = {}
        self.trades: list[dict[str, Any]] = []
        self.positions: list[dict[str, Any]] = []
        self.ring_customers: list[str] = []
        self.ring_accounts: list[str] = []

    # -- envelope plumbing ------------------------------------------------------------

    def _emit(
        self,
        kind: str,
        occurred_at: datetime,
        payload: dict[str, Any],
        entities: list[EntityRef],
    ) -> None:
        self._event_counter += 1
        self.envelopes.append(
            EventEnvelope(
                event_id=f"evt_demo_{self._event_counter:05d}",
                kind=kind,
                occurred_at=occurred_at,
                recorded_at=occurred_at,
                source=DEMO_SOURCE,
                entities=entities,
                payload=payload,
                episode_id=DEMO_EPISODE_ID,
                provenance=Provenance(
                    source_system=DEMO_SOURCE,
                    ingested_at=occurred_at,
                    licence="synthetic",
                    notes="generated demo book",
                ),
            )
        )

    # -- customers ---------------------------------------------------------------------

    def build_customers(self) -> None:
        names = ["Acme Corp Ltd"]
        for first in _CORP_FIRST[1:]:
            line = _CORP_LINES[int(self.rng.integers(0, len(_CORP_LINES)))]
            suffix = _CORP_SUFFIXES[int(self.rng.integers(0, len(_CORP_SUFFIXES)))]
            names.append(f"{first} {line} {suffix}")
        names.extend(_RETAIL_NAMES)

        for index, name in enumerate(names):
            customer_id = f"cus_{index + 1:04d}"
            corporate = index < len(_CORP_FIRST)
            in_ring = index in _RING_CUSTOMER_INDICES
            risk = (
                str(self.rng.choice(["medium", "high"], p=[0.5, 0.5]))
                if in_ring
                else str(self.rng.choice(["low", "medium", "high"], p=[0.7, 0.25, 0.05]))
            )
            record = {
                "customer_id": customer_id,
                "name": name,
                "segment": "sme" if corporate else "retail",
                "risk_rating": risk,
                "country": str(self.rng.choice(_COUNTRIES)),
            }
            self.customers.append(record)
            if in_ring:
                self.ring_customers.append(customer_id)
            opened = _BASE_DATE - timedelta(days=int(self.rng.integers(45, 720)))
            self._emit(
                "customer.created",
                opened,
                dict(record),
                [EntityRef(entity_type="customer", entity_id=customer_id)],
            )

    # -- accounts ----------------------------------------------------------------------

    def build_accounts(self) -> None:
        account_counter = 0

        def add_account(customer: dict[str, Any]) -> None:
            nonlocal account_counter
            account_counter += 1
            account_id = f"acc_{account_counter:04d}"
            currency = str(self.rng.choice(_CURRENCIES, p=[0.5, 0.25, 0.25]))
            account_type = str(self.rng.choice(_ACCOUNT_TYPES, p=[0.5, 0.35, 0.15]))
            balance = round(float(self.rng.uniform(2_500, 850_000)), 2)
            opened = _BASE_DATE - timedelta(days=int(self.rng.integers(30, 600)))
            record = {
                "account_id": account_id,
                "customer_id": customer["customer_id"],
                "currency": currency,
                "account_type": account_type,
                "balance": balance,
                "opened_at": opened.isoformat(),
            }
            self.accounts.append(record)
            self.account_by_customer.setdefault(customer["customer_id"], []).append(account_id)
            self._emit(
                "account.created",
                opened,
                dict(record),
                [
                    EntityRef(entity_type="account", entity_id=account_id),
                    EntityRef(entity_type="customer", entity_id=customer["customer_id"]),
                ],
            )

        for customer in self.customers:
            add_account(customer)
        for index in _SECOND_ACCOUNT_INDICES:
            add_account(self.customers[index])
        self.ring_accounts = [
            self.account_by_customer[customer_id][0] for customer_id in self.ring_customers
        ]

    # -- instruments and prices ------------------------------------------------------------

    def build_instruments(self) -> None:
        listed = _BASE_DATE - timedelta(days=900)
        for instrument_id, symbol, asset_class, currency in INSTRUMENTS:
            self._emit(
                "market.instrument",
                listed,
                {
                    "instrument_id": instrument_id,
                    "symbol": symbol,
                    "asset_class": asset_class,
                    "currency": currency,
                },
                [EntityRef(entity_type="instrument", entity_id=instrument_id)],
            )

    def build_prices(self) -> None:
        """GBM mid-price paths with GARCH(1,1)-style volatility clustering."""
        for instrument_id, symbol, _, currency in INSTRUMENTS:
            start_price = float(self.rng.uniform(18.0, 240.0))
            drift = float(self.rng.uniform(-0.05, 0.15)) / 252.0
            annual_vol = float(self.rng.uniform(0.12, 0.45))
            base_var = (annual_vol / math.sqrt(252.0)) ** 2
            alpha, beta = 0.09, 0.88
            omega = base_var * (1.0 - alpha - beta)
            shocks = self.rng.standard_normal(_N_PRICE_DAYS)

            price = start_price
            variance = base_var
            last_return = 0.0
            path: list[float] = []
            for day in range(_N_PRICE_DAYS):
                variance = omega + alpha * last_return**2 + beta * variance
                last_return = drift - 0.5 * variance + math.sqrt(variance) * float(shocks[day])
                price *= math.exp(last_return)
                mid = round(price, 4)
                path.append(mid)
                self._emit(
                    "market.price",
                    _bday(day),
                    {
                        "instrument_id": instrument_id,
                        "mid": mid,
                        "tags": {"symbol": symbol, "currency": currency},
                    },
                    [EntityRef(entity_type="instrument", entity_id=instrument_id)],
                )
            self.prices[instrument_id] = path

    # -- laundering ring ---------------------------------------------------------------------

    def build_ring_transfers(self) -> None:
        """Four rounds of sub-threshold transfers cycling through the 6 ring accounts."""
        ring = self.ring_accounts
        for round_index in range(4):
            for leg in range(len(ring)):
                src = ring[leg]
                dst = ring[(leg + 1) % len(ring)]
                amount = round(float(self.rng.uniform(8_600, 9_900)), 2)
                when = _bday(round_index * len(ring) + leg, hour=14, minute=5)
                self._emit(
                    "account.transfer",
                    when,
                    {
                        "from_account_id": src,
                        "to_account_id": dst,
                        "amount": amount,
                        "currency": "USD",
                        "reference": f"invoice settlement {round_index + 1}-{leg + 1}",
                    },
                    [
                        EntityRef(entity_type="account", entity_id=src),
                        EntityRef(entity_type="account", entity_id=dst),
                    ],
                )

    # -- trades and positions ------------------------------------------------------------------

    def build_trades(self) -> None:
        account_ids = [account["account_id"] for account in self.accounts]
        for trade_index in range(_N_TRADES):
            trade_id = f"trd_{trade_index + 1:04d}"
            account_id = account_ids[int(self.rng.integers(0, len(account_ids)))]
            instrument_id, symbol, _, currency = INSTRUMENTS[
                int(self.rng.integers(0, len(INSTRUMENTS)))
            ]
            day = int(self.rng.integers(0, _N_PRICE_DAYS))
            side = "buy" if float(self.rng.random()) < 0.55 else "sell"
            quantity = float(self.rng.integers(10, 500))
            price = round(
                self.prices[instrument_id][day] * (1.0 + float(self.rng.normal(0.0, 0.001))),
                4,
            )
            executed_at = _bday(day, hour=10, minute=30) + timedelta(
                minutes=int(self.rng.integers(0, 300))
            )
            record = {
                "trade_id": trade_id,
                "account_id": account_id,
                "instrument_id": instrument_id,
                "side": side,
                "quantity": quantity,
                "price": price,
                "currency": currency,
                "venue": "XOFF",
                "executed_at": executed_at.isoformat(),
            }
            self.trades.append(record)
            self._emit(
                "trade.executed",
                executed_at,
                dict(record),
                [
                    EntityRef(entity_type="trade", entity_id=trade_id),
                    EntityRef(entity_type="account", entity_id=account_id),
                    EntityRef(entity_type="instrument", entity_id=instrument_id),
                ],
            )

    def build_positions(self) -> None:
        nets: dict[tuple[str, str], float] = {}
        for trade in self.trades:
            key = (trade["account_id"], trade["instrument_id"])
            signed = trade["quantity"] if trade["side"] == "buy" else -trade["quantity"]
            nets[key] = nets.get(key, 0.0) + signed
        as_of = _bday(_N_PRICE_DAYS - 1, hour=18, minute=0)
        for (account_id, instrument_id), quantity in sorted(nets.items()):
            if quantity == 0.0:
                continue
            market_value = round(quantity * self.prices[instrument_id][-1], 2)
            record = {
                "account_id": account_id,
                "instrument_id": instrument_id,
                "quantity": quantity,
                "market_value": market_value,
            }
            self.positions.append(record)
            self._emit(
                "position.snapshot",
                as_of,
                dict(record),
                [
                    EntityRef(entity_type="account", entity_id=account_id),
                    EntityRef(entity_type="instrument", entity_id=instrument_id),
                ],
            )

    # -- cases and alerts -------------------------------------------------------------------------

    def build_cases_and_alerts(self) -> None:
        ring_customer_refs = [
            EntityRef(entity_type="customer", entity_id=c) for c in self.ring_customers
        ]
        ring_account_refs = [
            EntityRef(entity_type="account", entity_id=a) for a in self.ring_accounts
        ]
        opened = _bday(26, hour=9, minute=15)

        cases: list[dict[str, Any]] = [
            {
                "case_id": "case_0001",
                "kind": "aml_alert",
                "priority": "high",
                "status": "open",
                "narrative": (
                    "Transaction monitoring has identified a ring of six linked "
                    "accounts cycling transfers of 8,600 to 9,900 USD between one "
                    "another over four consecutive weeks. Every transfer sits just "
                    "below the 10,000 reporting threshold, a classic structuring "
                    "(smurfing) pattern. Funds return to the originating account "
                    "after passing through all six accounts, consistent with "
                    "layering. The customers involved are recently onboarded SMEs "
                    "with shared address fragments. Escalate to the MLRO under the "
                    "AML escalation procedure."
                ),
                "entities": ring_customer_refs + ring_account_refs,
            },
            {
                "case_id": "case_0002",
                "kind": "complaint",
                "priority": "medium",
                "status": "open",
                "narrative": (
                    "Retail customer reports a delayed outbound EUR payment that "
                    "left the account but did not reach the beneficiary for nine "
                    "business days. The customer incurred a late-payment penalty "
                    "from their landlord and requests redress for the fee and "
                    "interest. Payment trace requested; remediation matrix applies."
                ),
                "entities": [
                    EntityRef(entity_type="customer", entity_id="cus_0026"),
                    EntityRef(
                        entity_type="account",
                        entity_id=self.account_by_customer["cus_0026"][0],
                    ),
                ],
            },
            {
                "case_id": "case_0003",
                "kind": "complaint",
                "priority": "low",
                "status": "open",
                "narrative": (
                    "Customer disputes a 640 GBP custody fee charged to a savings "
                    "account, stating the fee schedule provided at onboarding "
                    "quoted a lower tier. Fee above the 500 threshold, so senior "
                    "handler review is required under the complaints handling "
                    "standard."
                ),
                "entities": [
                    EntityRef(entity_type="customer", entity_id="cus_0030"),
                    EntityRef(
                        entity_type="account",
                        entity_id=self.account_by_customer["cus_0030"][0],
                    ),
                ],
            },
            {
                "case_id": "case_0004",
                "kind": "limit_breach",
                "priority": "high",
                "status": "open",
                "narrative": (
                    "Active intraday breach of the daily gross notional trading "
                    "limit on a corporate trading account dealing in ALPH equity. "
                    "Pre-trade checks were bypassed by an aggregated order split. "
                    "Desk supervisor notified, position frozen for new risk, "
                    "remediation plan due to market risk per the trading limits "
                    "policy."
                ),
                "entities": [
                    EntityRef(entity_type="customer", entity_id="cus_0002"),
                    EntityRef(
                        entity_type="account",
                        entity_id=self.account_by_customer["cus_0002"][0],
                    ),
                    EntityRef(entity_type="instrument", entity_id="ins_ALPH"),
                ],
            },
            {
                "case_id": "case_0005",
                "kind": "kyc_refresh",
                "priority": "medium",
                "status": "open",
                "narrative": (
                    "Periodic KYC refresh for a medium-risk corporate customer is "
                    "94 days overdue. Ownership structure documents and source of "
                    "funds evidence have not been re-certified. Account "
                    "restrictions apply automatically at 120 days under the "
                    "onboarding standard."
                ),
                "entities": [EntityRef(entity_type="customer", entity_id="cus_0005")],
            },
            {
                "case_id": "case_0006",
                "kind": "fraud_review",
                "priority": "high",
                "status": "open",
                "narrative": (
                    "Suspected account takeover on a retail account: password "
                    "reset from a new device followed within minutes by the "
                    "addition of an unrecognised payee and two rapid outbound "
                    "transfers. Customer contacted via verified channel and denies "
                    "initiating the activity. Outbound payments held pending "
                    "review."
                ),
                "entities": [
                    EntityRef(entity_type="customer", entity_id="cus_0035"),
                    EntityRef(
                        entity_type="account",
                        entity_id=self.account_by_customer["cus_0035"][0],
                    ),
                ],
            },
        ]
        for offset, case in enumerate(cases):
            case_ref = EntityRef(entity_type="case", entity_id=case["case_id"])
            self._emit(
                "case.opened",
                opened + timedelta(days=offset),
                {
                    "case_id": case["case_id"],
                    "kind": case["kind"],
                    "priority": case["priority"],
                    "status": case["status"],
                    "narrative": case["narrative"],
                },
                [case_ref, *case["entities"]],
            )

        alerts = [
            {
                "alert_id": "alr_0001",
                "kind": "alert.structuring",
                "severity": "high",
                "score": 0.91,
                "status": "new",
                "entities": ring_account_refs,
            },
            {
                "alert_id": "alr_0002",
                "kind": "alert.velocity",
                "severity": "medium",
                "score": 0.74,
                "status": "new",
                "entities": [ring_account_refs[0]],
            },
        ]
        for offset, alert in enumerate(alerts):
            alert_ref = EntityRef(entity_type="alert", entity_id=alert["alert_id"])
            self._emit(
                alert["kind"],
                _bday(25, hour=7, minute=45) + timedelta(hours=offset),
                {
                    "alert_id": alert["alert_id"],
                    "severity": alert["severity"],
                    "score": alert["score"],
                    "status": alert["status"],
                },
                [alert_ref, *alert["entities"]],
            )

    # -- policies ---------------------------------------------------------------------------------

    def build_policies(self) -> None:
        effective = _BASE_DATE - timedelta(days=365)
        for policy in _POLICIES:
            self._emit(
                "policy.published",
                effective,
                {
                    "policy_id": policy["policy_id"],
                    "title": policy["title"],
                    "body": policy["body"],
                    "tags": list(policy["tags"]),
                    "version": "1.0",
                },
                [EntityRef(entity_type="policy", entity_id=policy["policy_id"])],
            )

    # -- cash ladders ---------------------------------------------------------------------------

    def build_cash_ladders(self) -> None:
        """30-day projected cumulative net cash per currency, with a stress dip."""
        as_of = _bday(_N_PRICE_DAYS - 1, hour=7, minute=0)
        bases = {"USD": 140_000_000.0, "EUR": 90_000_000.0, "GBP": 65_000_000.0}
        for currency, base in bases.items():
            level = base
            stress_bucket = int(self.rng.integers(8, 22))
            for bucket in range(_N_CASH_BUCKETS):
                drift = float(self.rng.normal(0.0, 0.012)) * base
                level += drift
                if bucket == stress_bucket:
                    level -= 0.08 * base  # a lumpy contractual outflow
                value = round(level, 2)
                self._emit(
                    "market.cash_ladder",
                    as_of + timedelta(days=bucket),
                    {
                        "series_key": f"cash_ladder:{currency}",
                        "value": value,
                        "tags": {"currency": currency, "bucket_days": bucket},
                    },
                    [],
                )

    # -- orchestration -----------------------------------------------------------------------------

    def build(self) -> tuple[list[EventEnvelope], dict[str, Any]]:
        self.build_customers()
        self.build_accounts()
        self.build_instruments()
        self.build_prices()
        self.build_ring_transfers()
        self.build_trades()
        self.build_positions()
        self.build_cases_and_alerts()
        self.build_policies()
        self.build_cash_ladders()
        summary = {
            "seed": self.seed,
            "customers": len(self.customers),
            "accounts": len(self.accounts),
            "instruments": len(INSTRUMENTS),
            "trades": len(self.trades),
            "positions": len(self.positions),
            "cases": 6,
            "alerts": 2,
            "policies": len(_POLICIES),
            "price_days": _N_PRICE_DAYS,
            "cash_currencies": ["USD", "EUR", "GBP"],
            "ring_customers": list(self.ring_customers),
            "ring_accounts": list(self.ring_accounts),
            "envelopes": len(self.envelopes),
        }
        return self.envelopes, summary


def build_demo_book(seed: int = 7) -> tuple[list[EventEnvelope], dict[str, Any]]:
    """Generate the demo book as ``(envelopes, summary)`` without ingesting it.

    The same seed always produces an identical envelope stream (identical
    event ids, payloads and timestamps).
    """
    return _DemoBookBuilder(seed).build()


def load_demo_data(ingestor: EventIngestor, seed: int = 7) -> dict[str, Any]:
    """Generate the demo book and ingest it through the given ingestor.

    Returns the generation summary (entity counts, ring membership, envelope
    count) for auditing and demos.
    """
    envelopes, summary = build_demo_book(seed)
    for envelope in envelopes:
        ingestor.ingest(envelope)
    return summary
