"""Risk-sensitive reward shaping from the FinTwinOS founding brief.

The founding brief mandates that any learned policy optimises *business gain
net of risk and human cost*, with fixed, auditable weights rather than
tunable-by-the-agent knobs:

====================  ======  =========================================
Term                  Weight  Meaning
====================  ======  =========================================
expected shortfall      2.0   tail-risk created by the action
policy violation        5.0   any breach of a governance rule
human minutes           1.0   analyst / approver time consumed (per hour
                              equivalent is intentional: minutes weighted
                              1.0 keeps the unit explicit in logs)
latency                 0.5   delay imposed on the business process
====================  ======  =========================================

These live here, in one place, so the reward used by environments, offline
learners and shadow evaluation is provably identical.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np

__all__ = ["BriefWeights", "expected_shortfall", "risk_sensitive_reward"]


@dataclass(frozen=True, slots=True)
class BriefWeights:
    """The founding-brief reward weights (immutable by design).

    Attributes:
        business_gain: Multiplier on the raw business gain term (default 1.0).
        expected_shortfall: Penalty weight on tail risk (default 2.0).
        policy_violation: Penalty weight on governance breaches (default 5.0).
        human_minutes: Penalty weight on human time consumed (default 1.0).
        latency: Penalty weight on added process latency (default 0.5).
    """

    business_gain: float = 1.0
    expected_shortfall: float = 2.0
    policy_violation: float = 5.0
    human_minutes: float = 1.0
    latency: float = 0.5


def risk_sensitive_reward(
    business_gain: float,
    expected_shortfall_penalty: float,
    policy_violation_penalty: float,
    human_minutes_used: float,
    latency_penalty: float,
    weights: BriefWeights | None = None,
) -> float:
    """Combine the brief's reward terms into one scalar.

    ``reward = w_g * gain - w_es * ES - w_pv * violations - w_hm * minutes - w_l * latency``

    All penalty arguments are supplied as non-negative magnitudes; the
    subtraction (and therefore the sign convention) lives here so call sites
    cannot accidentally double-negate a term.

    Args:
        business_gain: Raw business value generated by the action.
        expected_shortfall_penalty: Tail-risk magnitude (e.g. from
            :func:`expected_shortfall` over simulated loss samples).
        policy_violation_penalty: Count or severity-weighted magnitude of
            governance violations triggered.
        human_minutes_used: Human time the action consumed, in minutes.
        latency_penalty: Latency magnitude added to the process.
        weights: Override weights; defaults to the founding-brief
            :class:`BriefWeights`.

    Returns:
        The scalar risk-sensitive reward.
    """
    w = weights or BriefWeights()
    return float(
        w.business_gain * business_gain
        - w.expected_shortfall * expected_shortfall_penalty
        - w.policy_violation * policy_violation_penalty
        - w.human_minutes * human_minutes_used
        - w.latency * latency_penalty
    )


def expected_shortfall(samples: np.ndarray | list[float], alpha: float = 0.95) -> float:
    """Expected shortfall (CVaR) of a loss distribution, in pure numpy.

    Convention: ``samples`` are *losses* — larger values are worse. The
    expected shortfall at level ``alpha`` is the mean of the worst
    ``(1 - alpha)`` tail, computed over the ``k = ceil((1 - alpha) * n)``
    largest samples (with ``k >= 1`` so the statistic is always defined).

    This discrete-tail definition is exactly hand-checkable: for 20 samples at
    ``alpha=0.95`` it is the single largest loss; at ``alpha=0.90`` it is the
    mean of the two largest.

    Args:
        samples: Loss samples (any shape; flattened).
        alpha: Confidence level in ``[0, 1)``; mass ``1 - alpha`` sits in the
            averaged tail.

    Returns:
        The mean of the worst ``(1 - alpha)`` fraction of samples.

    Raises:
        ValueError: On an empty sample set or ``alpha`` outside ``[0, 1)``.
    """
    arr = np.asarray(samples, dtype=np.float64).ravel()
    if arr.size == 0:
        raise ValueError("expected_shortfall requires at least one sample")
    if not 0.0 <= alpha < 1.0:
        raise ValueError(f"alpha must be in [0, 1), got {alpha}")
    # The 1e-12 guard absorbs float fuzz: (1 - 0.95) * 20 is 1.0000000000000009
    # in IEEE-754, and must count as exactly one tail sample, not two.
    k = max(1, int(np.ceil((1.0 - alpha) * arr.size - 1e-12)))
    tail = np.sort(arr)[-k:]
    return float(tail.mean())
